cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "heroku/brew"

cask "google-chrome"
cask "emacs"
cask "visual-studio-code"
cask "dbeaver-community"
cask "alfred"
cask "mark-text"
cask "postman"
cask "drawio"
cask "font-jetbrains-mono"
cask "choosy"

cask "docker"
brew "docker"

brew "asdf"
brew "tmux"
brew "jq"
brew "ag"
brew "jump"
brew "pure"
brew "mas"
brew "fzf"
brew "tree"
brew "bat"
brew "gpg"
brew "zplug"
brew "heroku"
brew "awscli"
brew "git"
brew "git-lfs"
brew "mysql-connector-c"
brew "shared-mime-info"
brew "yarn"
brew "hstr"

mas "Xcode ", id: 497799835
mas "RunCat (9.6)", id: 1429033973