#
# Executes commands at logout.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Execute code only if STDERR is bound to a TTY.
[[ -o INTERACTIVE && -t 2 ]] && {

SAYINGS=(
    "So long and thanks for all the fish.\n  -- Douglas Adams"
    "Good morning! And in case I don't see ya, good afternoon, good evening and goodnight.\n  --Truman Burbank"
    "The purpose of our lives is to be happy.\n  —- Dalai Lama"
    "You only live once, but if you do it right, once is enough.\n  -— Mae West"
    "Turn your wounds into wisdom.\n  -— Oprah Winfrey"
    "I like criticism. It makes you strong.\n  -— LeBron James"
)

# Print a randomly-chosen message:
echo $SAYINGS[$(($RANDOM % ${#SAYINGS} + 1))]

} >&2
