#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#--------------------------------------------------------
# zinit
#--------------------------------------------------------
source /usr/local/opt/zinit/zinit.zshex
# 使用したいpluginを記載
zinit self-update

#--------------------------------------------------------
# prezto
#--------------------------------------------------------
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
  autoload 3-U promptinit; promptinit
  prompt pure
fi

# Customize to your needs...
#--------------------------------------------------------
# asdf(arm64) / anyenv(x86_64)
#--------------------------------------------------------
[ `uname -m` = 'arm64' ] && . /opt/homebrew/opt/asdf/libexec/asdf.sh
[ `uname -m` = 'x86_64' ] && eval "$(anyenv init -)"

#--------------------------------------------------------
# jump
#--------------------------------------------------------
eval "$(jump shell)"

#--------------------------------------------------------
# alias
#--------------------------------------------------------
alias la="ls -aFG"
alias ls="ls -FG"
alias ll="ls -alFG"
alias dc="docker-compose"
alias do="docker"
alias brewx="arch -x86_64 /usr/local/bin/brew"
#--------------------------------------------------------
# path
#--------------------------------------------------------
# see zprofile.

#--------------------------------------------------------
# functions
#--------------------------------------------------------
function md (){
  open -a Typora $1
}

# docker hubのイメージタグを検索する関数
function docker-tags {
  curl -s https://registry.hub.docker.com/v1/repositories/$1/tags | jq -r '.[].name'
}